### ISSUE TITLE
Security with Password protect

### ISSUE THREAD

**Issue by gvsurenderreddy** [rinsuki/wstunnel#2]
Hello is there anyway to protect the connection with username and password or just password or a key phase  or something please .

wstunnel server 0.0.0.0:8888 127.0.0.1:25565  -secret=secret

wstunnel client 127.0.0.1:25565 ws://server:8888/ws  -secret=secret

**Comment by rinsuki** [comment]
Please use nginx or something reverse proxy, or implement to upstream tcp server.

I maybe accepting basic auth (e.g. ws://user:pass@example.com) in URL by client, but it is not tested (depend to upstream websocket library). so if not working, please create issue.
